version: 1.0.{build}
branches:
  only:
    - master
skip_commits:
  message: /Updated.*\.(md)/

image: Visual Studio 2015

install:
  - ps: choco install make -y

before_build:
- cmd: nuget restore
build:
  project: Okta.OAuth.CodeFlow.sln
  publish_wap: true
  verbosity: minimal

artifacts:
  - path: Okta.OAuth.CodeFlow.zip
    name: OktaAuth-1.0.{build}

deploy:
  - provider: WebDeploy
    server: "https://dev-pricing.westeurope.cloudapp.azure.com:8172/MsDeploy.axd"
    website: OktaAuth
    username: agent-deploy
    password:
      secure: JgjViYedUd5IyB5V8dmwzPCt5qAAmxjM5fDd/ZZKAGc=
    ntlm: false
    remove_files: false
    app_offline: false
    do_not_use_checksum: true
    sync_retry_attempts: 2
    sync_retry_interval: 2000
    artifact: Okta.OAuth.CodeFlow.zip

environment:
  OAUTH_CLIENTID:
    secure: 5fD1d6Y1j/YTMZEg/eh2wxiNb2lDoObksT5LYxhXDO4=
  OAUTH_CLIENTSECRET:
    secure: bSkDXFV6HneYsKUlfEXibTIm9TGecEuwRfuBccrFNww3vCe4SlVr67tHIeilwkmd
  OAUTH_AUTHORITY:
    secure: XzBoi61+k8/lwT/F0Q55r4aZQ8hstE7sb0rouFXNsySrwst+0mP1ibG/DfWuChW0
