version: 1.0.{build}
branches:
  only:
    - master
skip_commits:
  message: /Updated.*\.(md)/

image: Visual Studio 2015

# install:
#   - ps: choco install make -y

before_build:
  - cmd: nuget restore
build:
  project: Okta.OAuth.CodeFlow.sln
  publish_wap: true
  verbosity: minimal
after_build:
  - ps: trigger.ps1 -project okta-auth-deployment -apiToken $env.API_TOKEN

environment:
  OAUTH_CLIENTID:
    secure: 5fD1d6Y1j/YTMZEg/eh2wxiNb2lDoObksT5LYxhXDO4=
  OAUTH_CLIENTSECRET:
    secure: bSkDXFV6HneYsKUlfEXibTIm9TGecEuwRfuBccrFNww3vCe4SlVr67tHIeilwkmd
  OAUTH_AUTHORITY:
    secure: XzBoi61+k8/lwT/F0Q55r4aZQ8hstE7sb0rouFXNsySrwst+0mP1ibG/DfWuChW0
  API_TOKEN:
    secure: K+Xh6Wc8vsAuJqeqdlNKh8ie7E1prS/yJ3XFQyGuHI8=
